// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABoP-ZMAPSB-gGSsHGNBMFLJBUEkrsPIE',
    appId: '1:257675957691:web:3d27589443bf2418fba09e',
    messagingSenderId: '257675957691',
    projectId: 'barber-shop-whitelabel',
    authDomain: 'barber-shop-whitelabel.firebaseapp.com',
    storageBucket: 'barber-shop-whitelabel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWSuX46JQEq3VDfSyAFciDMhjpn7YQMUI',
    appId: '1:257675957691:android:a2eb3db33f360085fba09e',
    messagingSenderId: '257675957691',
    projectId: 'barber-shop-whitelabel',
    storageBucket: 'barber-shop-whitelabel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRNr5mFoF5pnRpccyWCXPc_LO_Xo-9OgU',
    appId: '1:257675957691:ios:6ea1477d33f9711ffba09e',
    messagingSenderId: '257675957691',
    projectId: 'barber-shop-whitelabel',
    storageBucket: 'barber-shop-whitelabel.firebasestorage.app',
    androidClientId: '257675957691-1eosk65j475fbe8s2kq6lrkhd92im4ho.apps.googleusercontent.com',
    iosClientId: '257675957691-pg2dah6759019chvghtj5uotjsis113r.apps.googleusercontent.com',
    iosBundleId: 'com.tamebooking.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRNr5mFoF5pnRpccyWCXPc_LO_Xo-9OgU',
    appId: '1:257675957691:ios:6ea1477d33f9711ffba09e',
    messagingSenderId: '257675957691',
    projectId: 'barber-shop-whitelabel',
    storageBucket: 'barber-shop-whitelabel.firebasestorage.app',
    androidClientId: '257675957691-1eosk65j475fbe8s2kq6lrkhd92im4ho.apps.googleusercontent.com',
    iosClientId: '257675957691-pg2dah6759019chvghtj5uotjsis113r.apps.googleusercontent.com',
    iosBundleId: 'com.tamebooking.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiwQj3HRdMppv_dvwI4dwYcoWEc9ugrlM',
    appId: '1:257675957691:web:c29f272aaa622f3dfba09e',
    messagingSenderId: '257675957691',
    projectId: 'barber-shop-whitelabel',
    authDomain: 'barber-shop-whitelabel.firebaseapp.com',
    storageBucket: 'barber-shop-whitelabel.firebasestorage.app',
    measurementId: 'G-HPZGMKWV08',
  );

}